# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'WRWallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'CRBoxInputView', '~> 1.2.1'

  # Pods for WRWallet

end
